use_frameworks!
platform:ios, '10.0'
inhibit_all_warnings!

target 'HHPGNetWork_Example' do
  pod 'HHPGNetWork', :path => '../'

  target 'HHPGNetWork_Tests' do
    inherit! :search_paths

    
  end
end
